name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: ['main']
  merge_group:
    types: [checks_requested]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm install
      - run: npx playwright install --with-deps
      - uses: nrwl/nx-set-shas@v4

      - run: npm run all
