name: RELEASE

on:
  release:
    types: [published]

jobs:
  main:
    name: Build Docker Images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install
      - run: npx playwright install --with-deps
      - uses: nrwl/nx-set-shas@v4

      - name: Lint and Test
        run: npm run all

      - name: Build Backend
        run: npm run backend:build

      - name: Build Frontend
        run: npm run frontend:build

      - name: Log in to ghcr
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Backend Metadata
        id: metab
        uses: docker/metadata-action@v5.5.1
        with:
          images: ghcr.io/goncah/invenira-backend

      - name: Build and push Backend Docker image
        id: pushb
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./apps/backend/Dockerfile
          push: true
          tags: ${{ steps.metab.outputs.tags }}
          labels: ${{ steps.metab.outputs.labels }}

      - name: Extract Frontend Metadata
        id: metaf
        uses: docker/metadata-action@v5.5.1
        with:
          images: ghcr.io/goncah/invenira-frontend

      - name: Build and Push Frontend Docker image
        id: pushf
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./apps/frontend/Dockerfile
          push: true
          tags: ${{ steps.metaf.outputs.tags }}
          labels: ${{ steps.metaf.outputs.labels }}
